# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  playinventoryservice:
    image: play.inventory
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_PAT
    ports:
      - 5004:5004
    environment:
      - ServiceSettings__MessageBroker
      - MongoDbSettings__Host
      - MongoDbSettings__Port
      - MongoDbSettings__ConnectionString
      - RabbitMQSettings__Host
      - ServiceBusSettings__ConnectionString
      - IdentitySettings__AdminUserPassword
    networks:
      - pe-network

networks:
  pe-network:
    external: true
    name: pe-network
    driver: bridge