# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  playinventoryservice:
    image: play.inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
