apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: inventory-serviceaccount
      containers:
      - name: inventory
        image: playeconomy1384.azurecr.io/play.inventory:1.0.7
        env:
        - name: ServiceSettings__MessageBroker
          value: SERVICEBUS
        - name: ServiceSettings__KeyVaultName
          value: playeconomy1384
        - name: ServiceSettings__Authority
          value: https://playeconomy1384.northeurope.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: "/health/live"
            port: 5004
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/health/ready"
            port: 5004
          initialDelaySeconds: 10
          
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
  - port: 80
    targetPort: 5004

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-serviceaccount
  annotations:
    azure.workload.identity/client-id: dad6a3e7-3d03-4a1c-8637-bac01cf14919
  labels:
    azure.workload.identity/use: "true"
