microserviceName: inventory

image:
  repository: playeconomy1384.azurecr.io/play.inventory
  tag: 1.0.7

envVariables:
  IdentitySettings__PathBase: /inventory-svc
  ServiceSettings__Authority: https://playeconomy1384.northeurope.cloudapp.azure.com/identity-svc

resources:
  limits:
    memory: "256Mi"
    cpu: "200m"

container:
  port: 5004

serviceAccount:
  clientId: dad6a3e7-3d03-4a1c-8637-bac01cf14919